#!/usr/bin/env python3
"""
Build a comprehensive, offline-fallback catalog of heat-pump specs from the
NEEP ASHP database (https://ashp.neep.org). Runs server-side (CORS N/A).

Pulls every brand in NEEP concurrently, keeps records that carry the capacity
+ COP fields the balance-point math needs, and writes data/heatpumps.js.
The PWA uses this as a bundled seed; live lookups go through a CORS proxy /
Cloudflare Worker.
"""
import json
import sys
import time
import urllib.request
import urllib.parse
from concurrent.futures import ThreadPoolExecutor, as_completed

API = "https://ashp.neep.org/api/products/"
MAX_RECORDS = 12000
CONCURRENCY = 6

FIELDS = [
    "id", "brand", "model_number", "model_series",
    "outdoor_unit_number", "indoor_unit_number", "system_type",
    "heating_capacity_rated_47", "heating_capacity_max_5",
    "maintenance_capacity_rated17_rated47", "maintenance_capacity_5_47",
    "cop_max_5", "hspf_region_iv_2", "hspf_region_v_2",
    "lock_out_temp", "refrigerant", "ahri_certificate_number",
    "seer_2", "eer_2",
]


def fetch_json(url, timeout=40, retries=4):
    last = None
    for i in range(retries):
        try:
            req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
            with urllib.request.urlopen(req, timeout=timeout) as r:
                return json.loads(r.read().decode("utf-8"))
        except Exception as e:
            last = e
            time.sleep(1 + i)
    raise last


def get_brands():
    data = fetch_json(API + "get_brands")
    seen = set()
    out = []
    for b in data:
        key = b.strip().upper()
        if key and key not in seen:
            seen.add(key)
            out.append(b.strip())
    return out


def usable(rec):
    cap47 = rec.get("heating_capacity_rated_47")
    cap5 = rec.get("heating_capacity_max_5")
    cop5 = rec.get("cop_max_5")
    if not (cap47 and cap5 and cop5):
        return False
    key = (rec.get("outdoor_unit_number") or rec.get("model_number") or
           rec.get("model_series") or "").strip()
    return bool(key)


def fetch_brand(brand, seen, out, lock):
    added = 0
    for page in range(1, 8):
        if len(out) >= MAX_RECORDS:
            break
        try:
            url = API + "?" + urllib.parse.urlencode({
                "brand": brand, "page": page, "page_size": 100})
            data = fetch_json(url)
        except Exception:
            break
        if not data:
            break
        with lock:
            if len(out) >= MAX_RECORDS:
                break
            before = len(out)
            for rec in data:
                if not usable(rec):
                    continue
                k = (rec.get("outdoor_unit_number") or rec.get("model_number") or "").upper()
                if k in seen:
                    continue
                seen.add(k)
                out.append({f: rec.get(f) for f in FIELDS})
            added += len(out) - before
    return brand, added


def main():
    brands = get_brands()
    print(f"{len(brands)} brands", file=sys.stderr)
    seen = set()
    out = []
    lock = __import__("threading").Lock()
    with ThreadPoolExecutor(max_workers=CONCURRENCY) as ex:
        futs = [ex.submit(fetch_brand, b, seen, out, lock) for b in brands]
        for f in as_completed(futs):
            try:
                brand, added = f.result()
                if added:
                    print(f"{brand}: +{added} (total {len(out)})", file=sys.stderr)
            except Exception as e:
                print("brand error:", e, file=sys.stderr)
    out.sort(key=lambda r: (r.get("brand") or "", r.get("outdoor_unit_number") or r.get("model_number") or ""))
    out = out[:MAX_RECORDS]
    js = "// Auto-generated by scripts/fetch_catalog.py from the NEEP ASHP database.\n"
    js += "// Records keyed on outdoor_unit_number/model_series; trimmed to balance-point fields.\n"
    js += "window.HEAT_PUMP_DB = " + json.dumps(out, separators=(",", ":")) + ";\n"
    with open("data/heatpumps.js", "w", encoding="utf-8") as f:
        f.write(js)
    print(f"WROTE data/heatpumps.js with {len(out)} models", file=sys.stderr)


if __name__ == "__main__":
    main()
